// Package writer renders a migration as the Go source file that recreates
// it, serializing each operation's deconstructed arguments back into Go
// syntax.
//
// django: db/migrations/writer.py, db/migrations/serializer.py
package writer

import (
	"bytes"
	"cmp"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"maps"
	"math"
	"path"
	"path/filepath"
	"reflect"
	"regexp"
	"runtime"
	"slices"
	"strconv"
	"strings"
	"time"
	"unicode"

	m "github.com/ctolon/gormgate/migrations"
)

// MigrationsImport is the import path generated files use for the migration
// API, under the alias "m".
const MigrationsImport = "github.com/ctolon/gormgate/migrations"

// Version is the gormgate version named in the generated file's header.
// The root package installs the real one, read from the running program's
// build information; a test pins it to keep its golden files stable.
var Version = "(devel)"

// Now supplies the timestamp in the generated file's header. It is a
// variable so that tests can pin the clock.
var Now = time.Now

// Writer renders one migration.
//
// django: writer.py MigrationWriter
type Writer struct {
	// Migration is the migration to render.
	Migration *m.Migration
	// IncludeHeader adds the generated-by header to the output.
	IncludeHeader bool
	// PackageName is the Go package name of the migrations directory.
	PackageName string
	// PackagePath is the import path of the migrations package, used to
	// refer to functions defined in it without an import.
	PackagePath string

	// NeedsManualPorting is set when RunGo functions defined in other
	// migration files are referenced (they disappear when those files are
	// deleted after squashing).
	NeedsManualPorting bool
}

// SerializeError reports a value the writer cannot express as Go source.
type SerializeError struct{ Msg string }

func (e *SerializeError) Error() string { return e.Msg }

type imports struct {
	byPath  map[string]string // path -> alias
	byAlias map[string]string
}

func newImports() *imports {
	im := &imports{byPath: map[string]string{}, byAlias: map[string]string{}}
	im.byPath[MigrationsImport] = "m"
	im.byAlias["m"] = MigrationsImport
	return im
}

func (im *imports) alias(p string) string {
	if a, ok := im.byPath[p]; ok {
		return a
	}
	base := path.Base(p)
	base = strings.Map(func(r rune) rune {
		if unicode.IsLetter(r) || unicode.IsDigit(r) || r == '_' {
			return r
		}
		return '_'
	}, base)
	if base == "" || unicode.IsDigit(rune(base[0])) {
		base = "pkg_" + base
	}
	a := base
	for i := 2; ; i++ {
		if _, taken := im.byAlias[a]; !taken {
			break
		}
		a = base + strconv.Itoa(i)
	}
	im.byPath[p] = a
	im.byAlias[a] = p
	return a
}

type serializer struct {
	w      *Writer
	im     *imports
	manual map[string]bool // migration files whose functions are referenced
}

var migrationFileName = regexp.MustCompile(`^\d{4}_.*\.go$`)

// AsString renders the migration file.
//
// django: writer.py MigrationWriter.as_string
func (w *Writer) AsString() ([]byte, error) {
	s := &serializer{w: w, im: newImports(), manual: map[string]bool{}}
	var b strings.Builder
	mig := w.Migration

	var body strings.Builder
	body.WriteString("func init() {\n\tm.Register(&m.Migration{\n")
	fmt.Fprintf(&body, "App: %s,\n", strconv.Quote(mig.App))
	fmt.Fprintf(&body, "Name: %s,\n", strconv.Quote(mig.Name))
	if len(mig.Replaces) > 0 {
		body.WriteString("Replaces: " + s.keys(mig.Replaces) + ",\n")
	}
	if mig.IsInitial() {
		body.WriteString("Initial: m.Ptr(true),\n")
	}
	if !mig.IsAtomic() {
		body.WriteString("Atomic: m.Ptr(false),\n")
	}
	if len(mig.RunBefore) > 0 {
		body.WriteString("RunBefore: " + s.keys(mig.RunBefore) + ",\n")
	}
	deps := slices.Clone(mig.Dependencies)
	slices.SortFunc(deps, func(a, b m.Key) int {
		return cmp.Or(cmp.Compare(a.App, b.App), cmp.Compare(a.Name, b.Name))
	})
	body.WriteString("Dependencies: " + s.keys(deps) + ",\n")
	body.WriteString("Operations: []m.Operation{\n")
	for _, op := range mig.Operations {
		code, err := s.value(reflect.ValueOf(op))
		if err != nil {
			return nil, err
		}
		body.WriteString(code + ",\n")
	}
	body.WriteString("},\n})\n}\n")

	if w.IncludeHeader {
		fmt.Fprintf(&b, "// Generated by gormgate %s on %s\n\n", Version, Now().Format("2006-01-02 15:04"))
	}
	pkg := w.PackageName
	if pkg == "" {
		pkg = "migrations"
	}
	fmt.Fprintf(&b, "package %s\n\n", pkg)
	paths := slices.Sorted(maps.Keys(s.im.byPath))
	b.WriteString("import (\n")
	for _, p := range paths {
		alias := s.im.byPath[p]
		if alias == path.Base(p) && p != MigrationsImport {
			fmt.Fprintf(&b, "\t%s\n", strconv.Quote(p))
		} else {
			fmt.Fprintf(&b, "\t%s %s\n", alias, strconv.Quote(p))
		}
	}
	b.WriteString(")\n\n")
	if len(s.manual) > 0 {
		w.NeedsManualPorting = true
		files := slices.Sorted(maps.Keys(s.manual))
		b.WriteString("// Functions from the following migrations need manual copying.\n" +
			"// Move them and any dependencies into this file, then update the\n" +
			"// RunGo operations to refer to the local versions:\n// " + strings.Join(files, "\n// ") + "\n\n")
	}
	b.WriteString(body.String())
	out, err := format.Source([]byte(b.String()))
	if err != nil {
		return nil, fmt.Errorf("gormgate: generated migration does not parse: %w\n%s", err, b.String())
	}
	return out, nil
}

func (s *serializer) keys(keys []m.Key) string {
	if len(keys) == 0 {
		return "[]m.Key{}"
	}
	var parts []string
	for _, k := range keys {
		parts = append(parts, fmt.Sprintf("{App: %s, Name: %s}", strconv.Quote(k.App), strconv.Quote(k.Name)))
	}
	return "[]m.Key{\n" + strings.Join(parts, ",\n") + ",\n}"
}

var migrationsPkg = reflect.TypeOf(m.Field{}).PkgPath()

var dataTypeNames = map[m.DataType]string{
	m.Bool: "m.Bool", m.Int: "m.Int", m.Uint: "m.Uint", m.Float: "m.Float",
	m.String: "m.String", m.Time: "m.Time", m.Bytes: "m.Bytes",
}

var (
	typeOfDataType = reflect.TypeOf(m.DataType(""))
	typeOfTime     = reflect.TypeOf(time.Time{})
	typeOfGoExpr   = reflect.TypeOf(&m.GoExpr{})
	typeOfTypeRef  = reflect.TypeOf(&m.TypeRef{})
	typeOfDBDef    = reflect.TypeOf(&m.DBDefault{})
	typeOfFields   = reflect.TypeOf(m.Fields{})
)

// typeName renders the Go type of v for composite literals.
func (s *serializer) typeName(t reflect.Type) string {
	switch t.Kind() {
	case reflect.Pointer:
		return "*" + s.typeName(t.Elem())
	case reflect.Slice:
		// A named slice type keeps its name: m.Statements, not []string.
		// The field it is assigned to is declared as the interface that
		// named type implements, so the element type alone would not
		// compile.
		if t.Name() == "" {
			return "[]" + s.typeName(t.Elem())
		}
	case reflect.Map:
		if t.Name() == "" {
			return "map[" + s.typeName(t.Key()) + "]" + s.typeName(t.Elem())
		}
	case reflect.Interface:
		if t.PkgPath() == "" {
			return "any"
		}
	}
	if t.PkgPath() == "" {
		return t.String()
	}
	if t.PkgPath() == migrationsPkg {
		return "m." + t.Name()
	}
	return s.im.alias(t.PkgPath()) + "." + t.Name()
}

// elidesConversion reports whether a value of type t may be written as a bare
// untyped literal when the surrounding context (a struct field, a slice
// element, a map key or a map value) is declared with exactly that type. Go
// converts the untyped constant back to t on compilation, so the value read
// out of the generated file is identical, while the source keeps the plain
// spelling that migration files have always had.
//
// Only named string types qualify: they are the closed enumerations of the
// migration API (SortOrder, Deferrable, ReferentialAction), whose members are
// the SQL keywords themselves. DataType is excluded because it has named
// constants that read better than a quoted string.
func elidesConversion(t reflect.Type) bool {
	return t != nil && t.Kind() == reflect.String && t.PkgPath() != "" && t != typeOfDataType
}

// valueIn serializes v for a context whose declared type is want, eliding the
// conversion of a named string type that the context already supplies.
func (s *serializer) valueIn(v reflect.Value, want reflect.Type) (string, error) {
	if v.IsValid() && want != nil && v.Type() == want && elidesConversion(want) {
		return strconv.Quote(v.String()), nil
	}
	return s.value(v)
}

// value serializes v as a Go expression.
//
// django: serializer.py serializer_factory and the Serializer classes
func (s *serializer) value(v reflect.Value) (string, error) {
	if !v.IsValid() {
		return "nil", nil
	}
	t := v.Type()
	// A nil pointer is None, whatever it points at; checking this before the
	// type switch keeps the cases below from dereferencing it.
	if t.Kind() == reflect.Pointer && v.IsNil() {
		return "nil", nil
	}
	switch t {
	case typeOfDataType:
		if n, ok := dataTypeNames[m.DataType(v.String())]; ok {
			return n, nil
		}
		return strconv.Quote(v.String()), nil
	case typeOfTime:
		return s.timeValue(v.Interface().(time.Time)), nil
	case typeOfGoExpr:
		e := v.Interface().(*m.GoExpr)
		s.importsForExpr(e.Source)
		return e.Source, nil
	case typeOfTypeRef:
		r := v.Interface().(*m.TypeRef)
		if r.Package == "" {
			return "", &SerializeError{Msg: fmt.Sprintf("cannot serialize custom type %s: it has no package path", r.Name)}
		}
		return fmt.Sprintf("m.Custom[%s.%s]()", s.im.alias(r.Package), r.Name), nil
	case typeOfDBDef:
		d := v.Interface().(*m.DBDefault)
		if d.Expr != "" {
			return "m.DBExpr(" + strconv.Quote(d.Expr) + ")", nil
		}
		lit, err := s.literal(reflect.ValueOf(d.Value))
		if err != nil {
			return "", err
		}
		return "m.DBValue(" + lit + ")", nil
	}
	switch t.Kind() {
	case reflect.Func:
		return s.function(v)
	case reflect.Interface:
		if v.IsNil() {
			return "nil", nil
		}
		return s.value(v.Elem())
	case reflect.Pointer:
		if v.IsNil() {
			return "nil", nil
		}
		if t.Elem().Kind() == reflect.Struct {
			body, err := s.structBody(v.Elem())
			if err != nil {
				return "", err
			}
			return "&" + s.typeName(t.Elem()) + body, nil
		}
		lit, err := s.literal(v.Elem())
		if err != nil {
			return "", err
		}
		return "m.Ptr(" + lit + ")", nil
	case reflect.Struct:
		body, err := s.structBody(v)
		if err != nil {
			return "", err
		}
		return s.typeName(t) + body, nil
	case reflect.Slice, reflect.Array:
		if t.Kind() == reflect.Slice && v.IsNil() {
			return "nil", nil
		}
		if t == typeOfFields {
			return s.fields(v.Interface().(m.Fields))
		}
		// A byte string is written as a conversion of a quoted string,
		// which is the Go counterpart of the b'...' literal Django gets
		// from repr().
		//
		// django: serializer.py BaseSimpleSerializer (registered for bytes)
		if t.Kind() == reflect.Slice && t.Elem().Kind() == reflect.Uint8 && t.Elem().PkgPath() == "" {
			lit := fmt.Sprintf("[]byte(%s)", strconv.Quote(string(v.Bytes())))
			if t != reflect.TypeOf([]byte(nil)) {
				lit = s.typeName(t) + "(" + lit + ")"
			}
			return lit, nil
		}
		var parts []string
		// Composite literal elision: []T{{...}} and []*T{{...}}.
		elem := t.Elem()
		elide := ""
		if elem.Kind() == reflect.Struct {
			elide = s.typeName(elem)
		} else if elem.Kind() == reflect.Pointer && elem.Elem().Kind() == reflect.Struct {
			elide = "&" + s.typeName(elem.Elem())
		}
		for i := 0; i < v.Len(); i++ {
			p, err := s.valueIn(v.Index(i), elem)
			if err != nil {
				return "", err
			}
			if elide != "" {
				p = strings.TrimPrefix(p, elide)
			}
			parts = append(parts, p)
		}
		if len(parts) == 0 {
			return s.typeName(t) + "{}", nil
		}
		return s.typeName(t) + "{\n" + strings.Join(parts, ",\n") + ",\n}", nil
	case reflect.Map:
		if v.IsNil() {
			return "nil", nil
		}
		keys := v.MapKeys()
		slices.SortFunc(keys, func(a, b reflect.Value) int {
			return cmp.Compare(fmt.Sprint(a.Interface()), fmt.Sprint(b.Interface()))
		})
		var parts []string
		for _, k := range keys {
			ks, err := s.valueIn(k, t.Key())
			if err != nil {
				return "", err
			}
			vs, err := s.valueIn(v.MapIndex(k), t.Elem())
			if err != nil {
				return "", err
			}
			parts = append(parts, ks+": "+vs)
		}
		if len(parts) == 0 {
			return s.typeName(t) + "{}", nil
		}
		return s.typeName(t) + "{\n" + strings.Join(parts, ",\n") + ",\n}", nil
	}
	return s.literal(v)
}

func (s *serializer) fields(fs m.Fields) (string, error) {
	var parts []string
	for _, f := range fs {
		fv, err := s.value(reflect.ValueOf(f.Field))
		if err != nil {
			return "", err
		}
		parts = append(parts, fmt.Sprintf("{Name: %s, Field: %s}", strconv.Quote(f.Name), fv))
	}
	if len(parts) == 0 {
		return "m.Fields{}", nil
	}
	return "m.Fields{\n" + strings.Join(parts, ",\n") + ",\n}", nil
}

// structBody renders "{Field: value, ...}" with the non-zero exported
// fields in declaration order; embedded fields (baseOp) are skipped.
func (s *serializer) structBody(v reflect.Value) (string, error) {
	t := v.Type()
	var parts []string
	for i := range t.NumField() {
		sf := t.Field(i)
		if !sf.IsExported() || sf.Anonymous {
			continue
		}
		fv := v.Field(i)
		if fv.IsZero() {
			continue
		}
		code, err := s.valueIn(fv, sf.Type)
		if err != nil {
			return "", fmt.Errorf("%s.%s: %w", t.Name(), sf.Name, err)
		}
		parts = append(parts, sf.Name+": "+code)
	}
	if len(parts) == 0 {
		return "{}", nil
	}
	return "{\n" + strings.Join(parts, ",\n") + ",\n}", nil
}

// literal renders a scalar with its exact Go type so that values read back
// from the compiled migration compare equal.
func (s *serializer) literal(v reflect.Value) (string, error) {
	if !v.IsValid() {
		return "nil", nil
	}
	if v.Kind() == reflect.Interface {
		if v.IsNil() {
			return "nil", nil
		}
		v = v.Elem()
	}
	t := v.Type()
	if t == typeOfTime {
		return s.timeValue(v.Interface().(time.Time)), nil
	}
	if t == typeOfGoExpr {
		e := v.Interface().(*m.GoExpr)
		s.importsForExpr(e.Source)
		return e.Source, nil
	}
	named := t.PkgPath() != ""
	wrap := func(lit, defaultType string) string {
		if named {
			return s.typeName(t) + "(" + lit + ")"
		}
		if t.String() == defaultType {
			return lit
		}
		return t.String() + "(" + lit + ")"
	}
	switch t.Kind() {
	case reflect.Bool:
		return wrap(strconv.FormatBool(v.Bool()), "bool"), nil
	case reflect.String:
		return wrap(strconv.Quote(v.String()), "string"), nil
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		return wrap(strconv.FormatInt(v.Int(), 10), "int"), nil
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64, reflect.Uintptr:
		return wrap(strconv.FormatUint(v.Uint(), 10), ""), nil
	case reflect.Float32, reflect.Float64:
		f := v.Float()
		// Infinities and NaN have no literal syntax; they are written as the
		// math calls that produce them, like Django writes float("inf").
		//
		// django: serializer.py FloatSerializer
		switch {
		case math.IsInf(f, 1):
			s.im.alias("math")
			return wrap("math.Inf(1)", "float64"), nil
		case math.IsInf(f, -1):
			s.im.alias("math")
			return wrap("math.Inf(-1)", "float64"), nil
		case math.IsNaN(f):
			s.im.alias("math")
			return wrap("math.NaN()", "float64"), nil
		}
		lit := strconv.FormatFloat(f, 'g', -1, t.Bits())
		if !strings.ContainsAny(lit, ".eE") {
			lit += ".0"
		}
		return wrap(lit, "float64"), nil
	case reflect.Slice:
		if t.Elem().Kind() == reflect.Uint8 {
			return fmt.Sprintf("[]byte(%s)", strconv.Quote(string(v.Bytes()))), nil
		}
	case reflect.Func:
		return s.function(v)
	}
	switch t.Kind() {
	case reflect.Struct, reflect.Slice, reflect.Array, reflect.Map, reflect.Pointer, reflect.Interface:
		return s.value(v)
	}
	// Anything else (complex numbers, channels, unsafe pointers) has no
	// representation in a migration file.
	//
	// django: serializer.py serializer_factory
	return "", &SerializeError{Msg: fmt.Sprintf("cannot serialize: %v", v.Interface())}
}

func (s *serializer) timeValue(tv time.Time) string {
	s.im.alias("time")
	loc := "time.UTC"
	switch {
	case tv.Location() == time.UTC:
	case tv.Location() == time.Local:
		loc = "time.Local"
	default:
		name, offset := tv.Zone()
		loc = fmt.Sprintf("time.FixedZone(%s, %d)", strconv.Quote(name), offset)
	}
	return fmt.Sprintf("time.Date(%d, time.%s, %d, %d, %d, %d, %d, %s)",
		tv.Year(), tv.Month(), tv.Day(), tv.Hour(), tv.Minute(), tv.Second(), tv.Nanosecond(), loc)
}

// importsForExpr registers the imports a prompt-entered expression needs.
// Only the time package is offered at the prompt, so the expression is
// searched for a selector on the identifier "time"; a string literal that
// happens to contain "time." is not one.
func (s *serializer) importsForExpr(src string) {
	expr, err := parser.ParseExpr(src)
	if err != nil {
		return
	}
	ast.Inspect(expr, func(n ast.Node) bool {
		sel, ok := n.(*ast.SelectorExpr)
		if !ok {
			return true
		}
		if id, ok := sel.X.(*ast.Ident); ok && id.Name == "time" {
			s.im.alias("time")
		}
		return true
	})
}

var closureSuffix = regexp.MustCompile(`\.func\d+(\.\d+)*$`)

// function serializes a reference to a package-level function.
//
// django: serializer.py FunctionTypeSerializer
func (s *serializer) function(v reflect.Value) (string, error) {
	if v.IsNil() {
		return "nil", nil
	}
	fn := runtime.FuncForPC(v.Pointer())
	if fn == nil {
		return "", &SerializeError{Msg: "cannot serialize function: unknown"}
	}
	full := strings.TrimSuffix(fn.Name(), "-fm")
	if closureSuffix.MatchString(full) {
		return "", &SerializeError{Msg: "cannot serialize function: function literal " + full}
	}
	// full is "import/path.Name" or "import/path.(*T).Method".
	slash := strings.LastIndex(full, "/")
	dot := strings.Index(full[slash+1:], ".")
	if dot < 0 {
		return "", &SerializeError{Msg: "cannot serialize function: " + full}
	}
	pkgPath := full[:slash+1+dot]
	name := full[slash+1+dot+1:]
	// A method value's runtime name is "pkg.Type.Method" for a value
	// receiver and "pkg.(*Type).Method" for a pointer receiver; neither is a
	// package-level identifier that can be written into a migration.
	//
	// django: serializer.py FunctionTypeSerializer
	if strings.ContainsAny(name, "()*.") {
		return "", &SerializeError{Msg: fmt.Sprintf("could not find function %s in %s.\nPlease note that due to Go language limitations, you cannot serialize method values; use a package-level function", name, pkgPath)}
	}
	if file, _ := fn.FileLine(v.Pointer()); migrationFileName.MatchString(filepath.Base(file)) && pkgPath == s.w.PackagePath {
		// A function defined in another migration file of this package.
		if base := strings.TrimSuffix(filepath.Base(file), ".go"); !s.isOwnFile(base) {
			s.manual[strings.TrimSuffix(base, "_")] = true
		}
	}
	if pkgPath == s.w.PackagePath {
		return name, nil
	}
	if pkgPath == migrationsPkg {
		return "m." + name, nil
	}
	return s.im.alias(pkgPath) + "." + name, nil
}

func (s *serializer) isOwnFile(base string) bool {
	return strings.TrimSuffix(base, "_") == s.w.Migration.Name
}

// knownGOOSGOARCH are the file-name suffixes the go tool treats as build
// constraints.
var knownGOOSGOARCH = map[string]bool{}

func init() {
	for _, w := range strings.Fields(`aix android darwin dragonfly freebsd hurd illumos ios js linux nacl netbsd openbsd plan9 solaris wasip1 windows zos
386 amd64 amd64p32 arm armbe arm64 arm64be loong64 mips mipsle mips64 mips64le mips64p32 mips64p32le ppc ppc64 ppc64le riscv riscv64 s390 s390x sparc sparc64 wasm`) {
		knownGOOSGOARCH[w] = true
	}
}

// Filename returns the file name for a migration. A name whose last "_"
// segment is "test" or a GOOS/GOARCH value would be excluded from the build
// by the go tool, so such names get a trailing underscore.
//
// django: writer.py MigrationWriter.filename
func Filename(name string) string {
	parts := strings.Split(name, "_")
	last := parts[len(parts)-1]
	if last == "test" || knownGOOSGOARCH[last] {
		return name + "_.go"
	}
	return name + ".go"
}

// MigrationNameFromFile recovers the migration name from a file name,
// inverting Filename.
func MigrationNameFromFile(file string) string {
	base := strings.TrimSuffix(filepath.Base(file), ".go")
	if strings.HasSuffix(base, "_") {
		stripped := strings.TrimSuffix(base, "_")
		if Filename(stripped) == base+".go" {
			return stripped
		}
	}
	return base
}

// PackageFile renders the migrations.go file that registers the package
// directory with the loader.
func PackageFile(pkgName, app string) []byte {
	src := fmt.Sprintf(`// Package %s holds the migrations of app %q.
package %s

import m %q

func init() { m.RegisterPackage(%q) }
`, pkgName, app, pkgName, MigrationsImport, app)
	out, err := format.Source([]byte(src))
	if err != nil {
		panic(err)
	}
	return out
}

// LinkFile renders the file in the gorm-gate command's package that imports
// every app's migrations package so they are compiled in.
func LinkFile(pkgName string, importPaths []string) []byte {
	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by gormgate. DO NOT EDIT.\n\npackage %s\n\n", pkgName)
	sorted := slices.Sorted(slices.Values(importPaths))
	if len(sorted) > 0 {
		b.WriteString("import (\n")
		for _, p := range sorted {
			fmt.Fprintf(&b, "\t_ %s\n", strconv.Quote(p))
		}
		b.WriteString(")\n")
	}
	out, err := format.Source(b.Bytes())
	if err != nil {
		panic(err)
	}
	return out
}

// PackageNameOf returns the package name declared by the first of files in
// name order, or "" when none of them declares one.
func PackageNameOf(files map[string][]byte) string {
	for _, n := range slices.Sorted(maps.Keys(files)) {
		f, err := parser.ParseFile(token.NewFileSet(), n, files[n], parser.PackageClauseOnly)
		if err == nil {
			return f.Name.Name
		}
	}
	return ""
}
