// Generated by gormgate 0.1.0 on 2026-09-23 11:45

package migrations

import (
	m "github.com/ctolon/gormgate/migrations"
)

func init() {
	m.Register(&m.Migration{
		App:          "crm",
		Name:         "0001_initial",
		Initial:      m.Ptr(true),
		Dependencies: []m.Key{},
		Operations: []m.Operation{
			&m.CreateModel{
				Name:  "Customer",
				Table: "crm_customers",
				Fields: m.Fields{
					{Name: "id", Field: m.Field{
						Type:          m.Int,
						Size:          32,
						PrimaryKey:    true,
						AutoIncrement: true,
						Null:          true,
					}},
					{Name: "name", Field: m.Field{
						Type: "TEXT",
					}},
					{Name: "email", Field: m.Field{
						Type:   "TEXT",
						Unique: true,
					}},
					{Name: "signed_up", Field: m.Field{
						Type: m.Time,
						Null: true,
					}},
				},
			},
			&m.CreateModel{
				Name:  "Contract",
				Table: "crm_contracts",
				Fields: m.Fields{
					{Name: "id", Field: m.Field{
						Type:          m.Int,
						Size:          32,
						PrimaryKey:    true,
						AutoIncrement: true,
						Null:          true,
					}},
					{Name: "value_cents", Field: m.Field{
						Type: m.Int,
						Size: 32,
					}},
					{Name: "customer_id", Field: m.Field{
						Type: m.Int,
						Size: 32,
						Tags: map[string]string{
							"INDEX": "INDEX",
						},
						ForeignKey: &m.ForeignKey{
							To:      "crm.customer",
							ToField: "id",
							Name:    "fk_crm_contracts_customer",
						},
					}},
				},
				Options: m.Options{
					Indexes: []m.Index{
						{
							Name: "idx_crm_contracts_customer_id",
							Fields: []m.IndexField{
								{
									Column: "customer_id",
								},
							},
						},
					},
				},
			},
		},
	})
}
