// Generated by gormgate 0.1.0 on 2026-09-23 11:44

package migrations

import (
	m "github.com/ctolon/gormgate/migrations"
)

func init() {
	m.Register(&m.Migration{
		App:          "shop",
		Name:         "0001_initial",
		Initial:      m.Ptr(true),
		Dependencies: []m.Key{},
		Operations: []m.Operation{
			&m.CreateModel{
				Name:  "Order",
				Table: "shop_orders",
				Fields: m.Fields{
					{Name: "id", Field: m.Field{
						Type:          m.Uint,
						Size:          64,
						PrimaryKey:    true,
						AutoIncrement: true,
						Null:          true,
					}},
					{Name: "item", Field: m.Field{
						Type: m.String,
						Size: 100,
					}},
					{Name: "amount_cents", Field: m.Field{
						Type: m.Int,
						Size: 64,
					}},
				},
			},
		},
	})
}
