// Generated by gormgate 0.1.0 on 2026-09-23 11:44

package migrations

import (
	m "github.com/ctolon/gormgate/migrations"
)

func init() {
	m.Register(&m.Migration{
		App:          "analytics",
		Name:         "0001_initial",
		Initial:      m.Ptr(true),
		Dependencies: []m.Key{},
		Operations: []m.Operation{
			&m.CreateModel{
				Name:  "PageView",
				Table: "analytics_page_views",
				Fields: m.Fields{
					{Name: "id", Field: m.Field{
						Type:          m.Uint,
						Size:          64,
						PrimaryKey:    true,
						AutoIncrement: true,
						Null:          true,
					}},
					{Name: "path", Field: m.Field{
						Type: m.String,
						Size: 200,
						Tags: map[string]string{
							"INDEX": "INDEX",
						},
					}},
					{Name: "seen", Field: m.Field{
						Type: m.Time,
						Null: true,
					}},
				},
				Options: m.Options{
					Indexes: []m.Index{
						{
							Name: "idx_analytics_page_views_path",
							Fields: []m.IndexField{
								{
									Column: "path",
								},
							},
						},
					},
				},
			},
		},
	})
}
